name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install
          npm run build 
      - name: Upload build output 
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/
      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./downloaded