# .github/workflows/caller.yml
name: Call Reusable Build

on: [push]

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      mode: "production"
    
    secrets:
        MY_SECRET: ${{ secrets.MY_SECRET }}