name: GitHub Token Commit Example

on: [push]

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create file and commit
        run: |
          echo "hello from GITHUB_TOKEN" > hello.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add hello.txt
          git commit -m "Add hello.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
