# .github/workflows/reusable-build.yml
name: Reusable Build Workflow

on:
  workflow_call:
    secrets:
        MY_SECRET:
            required: true
    inputs:
      mode:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Mode
        run: echo "Build mode is ${{ inputs.mode }}"
