name: Secret Example

on: [push]

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Show a secret
        run: echo "My secret is ${{ secrets.MY_API_KEY }}"

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        run: echo "Hello, ${{ secrets.MY_NAME }}!"
